import unittest
import bioseq as bs

class PipelineTests(unittest.TestCase):

    fasta_desc = 'NP_000758.1 cytochrome P450 2B6 precursor [Homo sapiens]'
    fasta_seq = bs.ProteinSeq('MELSVLLFLALLTGLLLLLVQRHPNTHDRLPPGPRPLPLLGNLLQMDRRGLLKSFLRFREKYGDVFTVHLGPRPVVMLCGVEAIREALVDKAEAFSGRGKIAMVDPFFRGYGVIFANGNRWKVLRRFSVTTMRDFGMGKRSVEERIQEEAQCLIEELRKSKGALMDPTFLFQSITANIICSIVFGKRFHYQDQEFLKMLNLFYQTFSLISSVFGQLFELFSGFLKYFPGAHRQVYKNLQEINAYIGHSVEKHRETLDPSAPKDLIDTYLLHMEKEKSNAHSEFSHQNLNLNTLSLFFAGTETTSTTLRYGFLLMLKYPHVAERVYREIEQVIGPHRPPELHDRAKMPYTEAVIYEIQRFSDLLPMGVPHIVTQHTSFRGYIIPKDTEVFLILSTALHDPHYFEKPDAFNPDHFLDANGALKKTEAFIPFSLGKRICLGEGIARAELFLFFTTILQNFSMASPVAPEDIDLTPQECGVGKIPPTYQIRFLPR')

    def test_constructor(self):
        p = bs.pipeline('bioseq/res/source.fasta')
        self.assertEqual(p.desc, self.fasta_desc)
        self.assertEqual(p.seq, self.fasta_seq)

    def test_run_blast(self):
        p = bs.pipeline('bioseq/res/source.fasta', w=10)
        r = p.run_blast()
        print(r)