version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - run: python3 -m venv venv
      - run: . venv/bin/activate
      - run: pip3 install --user -r requirements.txt 
  test:
    docker:
      - image: circleci/python3:3.7
    steps:
      - checkout
      - run: python3 -m unittest test/*.py
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build